name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'dev'


jobs:
  terraform:
    name: "Destroy AWS"
    runs-on: ubuntu-latest
    env:
      working-directory: aws/backend
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
    steps:
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
              terraform_version: 1.9.8
              
        - name: Destroy resources jobs
          id: destroy
          run: terraform destroy -auto-approve -var=${{ secrets.folder_id }} -var=${{ secrets.cloud_id }} -var=${{ secrets.token }} -lock=false

